### ISSUE TITLE
Found multiple staging repositories

### ISSUE THREAD

**Issue by jamesward** [xerial/sbt-sonatype#83]
I'd like to do this:
```
sbt +publishSigned sonatypeRelease
```

But I often run into issues because there are multiple staging repos (due to other releases going on).  This also prevents me from using `sonatypeReleaseAll`.  Is there any way for `sonatypeRelease` to know what staging repo was created by `publishSigned` and use that?  Or maybe a new task that can publish and release?

**Comment by xerial** [comment]
Hi. Currently we can explicitly open a staging repository using `sonatypeOpen ...`, but it’s not convenient to use as we need to check the name of the staging repository created at Sonatype by looking at the display logs. 

I’ve been thinking re-designing sbt-sonatype so that we can seamlessly support concurrent releases and idempotent executions (upon any failures).

**Comment by jamesward** [comment]
Thanks! Wish I had some cycles to help. I'm so thankful for your plugin!

**Comment by tpolecat** [comment]
Yep, would also love to see a fix for this. A short-term solution might be to improve the error message and add `sonatypeDropAll` so there's an easy way to clean up and try again.

**Comment by pshirshov** [comment]
So, guys. Those who have issues with sbt publishing may drastically improve their experience by using this simple ant script:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:staging="antlib:org.sonatype.nexus.ant.staging">

    <taskdef uri="antlib:org.sonatype.nexus.ant.staging"
            resource="org/sonatype/nexus/ant/staging/antlib.xml">
    <classpath>
        <fileset dir="tasks" includes="nexus-staging-ant-tasks-*uber.jar" />
    </classpath>
    </taskdef>

    <staging:nexusStagingInfo id="target-nexus"
        stagingDirectory="staging">
    <staging:projectInfo groupId="org.sonatype.nexus.ant"
        artifactId="nexus-staging-ant-tasks"
        version="1.0" />
        <!-- https://oss.sonatype.org/service/local -->
    <staging:connectionInfo
        baseUrl="https://oss.sonatype.org/">
        <staging:authentication
        username="NEXUS-USER"
        password="NEXUS-PASSWORD" />
    </staging:connectionInfo>
    </staging:nexusStagingInfo>

    <target name="deploy" description="Deploy: Local and Remote Staging">
    <staging:stageLocally>
        <staging:nexusStagingInfo
            refid="target-nexus" />
        <fileset dir="repo"
            includes="**/*.*" />
        </staging:stageLocally>

    <staging:stageRemotely>
        <staging:nexusStagingInfo
            refid="target-nexus" />
    </staging:stageRemotely>
    </target>

</project>
```

More instructions [here](https://help.sonatype.com/repomanager2/staging-releases/configuring-your-project-for-deployment)

In order to prepare your artifacts for this script you would need the following sbt setting:

```
   publishTo := Some(Resolver.file("file", new File("/path/to/repo"))), 
```

In my case this simple trick allowed to decrease publishing time from ~40 minutes to 2 minutes...

**Comment by xerial** [comment]
@tpolecat sonatypeDropAll is added.

@jamesward sbt-sonatype 3.0 can support idempotent release with:
`; sonatypePrepare; publishSigned; sonatypeRelease`

Let me close the issue.

**Comment by pshirshov** [comment]
@xerial : it should fix the most annoying integrity issue, though it does not address insanely slow uploads. Maybe it's a good idea to incorporate a fast uploader into your plugin as well?..

**Comment by xerial** [comment]
@pshirshov I'd like to add such a feature to reduce my pain to upload artifacts. I still don't fully understand what your ant script does (rather what org.sonatype.nexus.ant.staging does) behind the scene. If I can understand the trick it would be possible to improve sbt-plugin.

**Comment by xerial** [comment]
It looks like stageRemotly function https://github.com/sonatype/nexus-ant-tasks/blob/master/nexus-staging-ant-tasks/src/main/java/org/sonatype/nexus/ant/staging/deploy/AbstractDeployTask.java#L111 is the corresponding code

**Comment by pshirshov** [comment]
Yeah, that's correct.

The ant script, essentially, just sends a zip file of the full maven layout to sonatype trough nexus-specific API.

**Comment by pshirshov** [comment]
Here is the method you are looking for: https://repository.sonatype.org/nexus-staging-plugin/default/docs/path__staging_bundle_upload.html

**Comment by xerial** [comment]
Nice. So instead of using publishSigned directly to sonatype repo:
1. Create a bundle (= the artifacts of publishLocalSigned)  locally
2. Upload it using the bundle upload API 
3. Do the regular close/promote step at Sonatype API

**Comment by xerial** [comment]
@pshirshov I'll move the discussion to #89 as the issue title doesn't match the conversation.
